In [168]:
import pandas as pd
import numpy as np

In [169]:
file = r"C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_2\Data\Part2.csv"
df1 = pd.read_csv(file)

#df1 = df1.dropna(subset=['player.Price_O_B'])

df1.drop(['participant._max_page_index','participant._current_app_name','participant._current_page_name', 'participant._index_in_pages',
          'participant._current_page_name','participant.time_started_utc','participant.visited'], inplace=True, axis=1)

df1 = df1.loc[:, (df1 != 0).any(axis=0)]
#df1c = df1.dropna(how='all', axis=1)
lenght=len(df1)
df1.index  = np.arange(lenght)

In [170]:
np.shape(df1)

(3960, 27)

In [ ]:
df1

In [171]:
df1[df1['participant.code']=='00yymq0o']

,treatment,participant.id_in_session,participant.code,player.id_in_group,player.random_block,player.random_order,player.control_question1,player.control_question2,player.alternative1,player.policy_choice,...,player.Price_O_B,player.EV_B,player.Revenue_B,player.attributes_binary_1,player.attributes_binary_2,player.attributes_binary_3,player.attributes_binary_4,player.attributes_binary_5,subsession.round_number,session.code
55,Baseline,56,00yymq0o,56,2.0,234210765.0,3.0,NaN,5.0,1.0,...,4.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,1,uln4i2w2
389,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,2.0,...,3.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,2,uln4i2w2
723,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,2.0,...,1.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,3,uln4i2w2
1057,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,2.0,...,3.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,4,uln4i2w2
1391,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,2.0,...,3.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,5,uln4i2w2
1725,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,2.0,...,2.0,3.0,2.0,NaN,NaN,NaN,NaN,NaN,6,uln4i2w2
2059,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,1.0,...,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,7,uln4i2w2
2393,Baseline,56,00yymq0o,56,2.0,234210765.0,NaN,NaN,NaN,1.0,...,4.0,3.0,5.0,0.0,0.0,0.0,0.0,0.0,8,uln4i2w2

In [172]:
print(df1.columns)

Index(['treatment', 'participant.id_in_session', 'participant.code',
       'player.id_in_group', 'player.random_block', 'player.random_order',
       'player.control_question1', 'player.control_question2',
       'player.alternative1', 'player.policy_choice', 'player.Price_UR_A',
       'player.Price_UN_A', 'player.Price_O_A', 'player.EV_A',
       'player.Revenue_A', 'player.Price_UR_B', 'player.Price_UN_B',
       'player.Price_O_B', 'player.EV_B', 'player.Revenue_B',
       'player.attributes_binary_1', 'player.attributes_binary_2',
       'player.attributes_binary_3', 'player.attributes_binary_4',
       'player.attributes_binary_5', 'subsession.round_number',
       'session.code'],
      dtype='object')

In [181]:
df1.rename(columns={'player.control_question1':'control_question1', 'player.control_question2':'control_question2',
       'player.alternative1':'alternative1','player.policy_choice':'policy_choice', 'player.Price_UR_A': 'Price_UR_A', 'player.Price_UN_A': 'Price_UN_A',
       'player.Price_O_A':'Price_O_A', 'player.EV_A': 'EV_A', 'player.Revenue_A': 'Revenue_A', 'player.Price_UR_B': 'Price_UR_B',
       'player.Price_UN_B': 'Price_UN_B',  'player.Price_O_B': 'Price_O_B', 'player.EV_B': 'EV_B', 'player.Revenue_B': 'Revenue_B',
       'player.attributes_binary_1': 'attributes_binary_1', 'player.attributes_binary_2': 'attributes_binary_2',
       'player.attributes_binary_3': 'attributes_binary_3', 'player.attributes_binary_4': 'attributes_binary_4',
       'player.attributes_binary_5': 'attributes_binary_5'}, inplace=True)

In [182]:
df1.to_csv(r"C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_2\Rearrange_datasets\Part2_long_format.csv", index=False)

In [174]:
# Assuming df1 is your original DataFrame
# Pivot the dataframe to create new columns for each policy choice and other player attributes
df_pivot = df1.pivot(index='participant.code', columns='subsession.round_number', 
                     values=['control_question1', 'control_question2',
                             'attributes_binary_1', 'attributes_binary_2', 'attributes_binary_3',
                             'attributes_binary_4', 'attributes_binary_5', 
                             'alternative1', 'policy_choice', 'Price_UR_A',
                             'Price_UN_A', 'Price_O_A', 'EV_A',
                             'Revenue_A', 'Price_UR_B', 'Price_UN_B',
                             'Price_O_B', 'EV_B', 'Revenue_B'])

# Flatten the multi-level columns and add the prefix
df_pivot.columns = [f'{int(col[1])}_{col[0]}' for col in df_pivot.columns]

# Reset the index to make 'participant.code' a column again
df_pivot.reset_index(inplace=True)

# Drop columns that are all NaN
df_pivot = df_pivot.dropna(axis=1, how='all')

df_pivot.rename(columns={'1_control_question1':'control_question1','1_control_question2':'control_question2','1_alternative1':'alternative1',
                            '8_attributes_binary_1':'attributes_binary_1', '8_attributes_binary_2':'attributes_binary_2',
                                '8_attributes_binary_3':'attributes_binary_3', '8_attributes_binary_4':'attributes_binary_4',
                                        '8_attributes_binary_5':'attributes_binary_5'}, inplace=True)
# Display the pivoted dataframe
df_pivot

,participant.code,control_question1,control_question2,attributes_binary_1,attributes_binary_2,attributes_binary_3,attributes_binary_4,attributes_binary_5,alternative1,1_policy_choice,...,7_EV_B,8_EV_B,1_Revenue_B,2_Revenue_B,3_Revenue_B,4_Revenue_B,5_Revenue_B,6_Revenue_B,7_Revenue_B,8_Revenue_B
0,00yymq0o,3.0,NaN,0.0,0.0,0.0,0.0,0.0,5.0,1.0,...,1.0,3.0,1.0,5.0,4.0,4.0,1.0,2.0,3.0,5.0
1,025baf3d,3.0,NaN,0.0,0.0,0.0,1.0,0.0,5.0,3.0,...,2.0,2.0,3.0,1.0,3.0,4.0,4.0,3.0,3.0,3.0
2,029z3dj5,3.0,NaN,0.0,0.0,0.0,1.0,0.0,5.0,1.0,...,3.0,2.0,3.0,3.0,3.0,1.0,3.0,4.0,5.0,4.0
3,04x8stxz,3.0,NaN,0.0,0.0,0.0,1.0,0.0,5.0,1.0,...,1.0,1.0,2.0,3.0,2.0,5.0,3.0,5.0,2.0,2.0
4,06u8w2cd,3.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,4.0,4.0,4.0,4.0,5.0,5.0,2.0,5.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,zuchyshq,3.0,NaN,0.0,1.0,1.0,0.0,0.0,5.0,1.0,...,2.0,1.0,5.0,4.0,4.0,4.0,4.0,3.0,2.0,2.0
491,zw6h1g9v,3.0,NaN,0.0,0.0,1.0,1.0,0.0,5.0,3.0,...,4.0,4.0,2.0,3.0,5.0,3.0,2.0,5.0,2.0,2.0
492,zx9q6r8j,3.0,NaN,0.0,1.0,0.0,0.0,0.0,3.0,2.0,...,2.0,2.0,4.0,1.0,5.0,2.0,1.0,4.0,3.0,1.0
493,zyp5jsph,3.0,NaN,0.0,0.0,1.0,1.0,0.0,5.0,2.0,...,3.0,4.0,2.0,4.0,5.0,1.0,5.0,2.0,3.0,5.0
494,zzfp66nz,1.0,2.0,1.0,0.0,1.0,1.0,0.0,2.0,2.0,...,2.0,3.0,3.0,1.0,1.0,2.0,5.0,5.0,5.0,4.0

In [175]:
np.shape(df_pivot)

(495, 97)

In [176]:
#drop rows that have nan in column control_question1
df_pivot = df_pivot.dropna(subset=['control_question1'])
df_pivot.reset_index(inplace=True, drop=True)

In [177]:
np.shape(df_pivot)

(485, 97)

In [178]:
df_pivot

,participant.code,control_question1,control_question2,attributes_binary_1,attributes_binary_2,attributes_binary_3,attributes_binary_4,attributes_binary_5,alternative1,1_policy_choice,...,7_EV_B,8_EV_B,1_Revenue_B,2_Revenue_B,3_Revenue_B,4_Revenue_B,5_Revenue_B,6_Revenue_B,7_Revenue_B,8_Revenue_B
0,00yymq0o,3.0,NaN,0.0,0.0,0.0,0.0,0.0,5.0,1.0,...,1.0,3.0,1.0,5.0,4.0,4.0,1.0,2.0,3.0,5.0
1,025baf3d,3.0,NaN,0.0,0.0,0.0,1.0,0.0,5.0,3.0,...,2.0,2.0,3.0,1.0,3.0,4.0,4.0,3.0,3.0,3.0
2,029z3dj5,3.0,NaN,0.0,0.0,0.0,1.0,0.0,5.0,1.0,...,3.0,2.0,3.0,3.0,3.0,1.0,3.0,4.0,5.0,4.0
3,04x8stxz,3.0,NaN,0.0,0.0,0.0,1.0,0.0,5.0,1.0,...,1.0,1.0,2.0,3.0,2.0,5.0,3.0,5.0,2.0,2.0
4,06u8w2cd,3.0,NaN,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,4.0,4.0,4.0,4.0,5.0,5.0,2.0,5.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
480,zuchyshq,3.0,NaN,0.0,1.0,1.0,0.0,0.0,5.0,1.0,...,2.0,1.0,5.0,4.0,4.0,4.0,4.0,3.0,2.0,2.0
481,zw6h1g9v,3.0,NaN,0.0,0.0,1.0,1.0,0.0,5.0,3.0,...,4.0,4.0,2.0,3.0,5.0,3.0,2.0,5.0,2.0,2.0
482,zx9q6r8j,3.0,NaN,0.0,1.0,0.0,0.0,0.0,3.0,2.0,...,2.0,2.0,4.0,1.0,5.0,2.0,1.0,4.0,3.0,1.0
483,zyp5jsph,3.0,NaN,0.0,0.0,1.0,1.0,0.0,5.0,2.0,...,3.0,4.0,2.0,4.0,5.0,1.0,5.0,2.0,3.0,5.0
484,zzfp66nz,1.0,2.0,1.0,0.0,1.0,1.0,0.0,2.0,2.0,...,2.0,3.0,3.0,1.0,1.0,2.0,5.0,5.0,5.0,4.0

In [179]:
#check

file = r"C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_2\Data\Part2.csv"
df3 = pd.read_csv(file)

for i in range(len(df3)):
     if df3['participant.code'][i] == 'ooxl8r2l':
            print(df3['player.policy_choice'][i])
            

f_df = df_pivot[df_pivot['participant.code'] == 'ooxl8r2l']
print(f_df['1_policy_choice'],f_df['2_policy_choice'],f_df['3_policy_choice'],f_df['4_policy_choice'],
      f_df['5_policy_choice'],f_df['6_policy_choice'],f_df['7_policy_choice'],f_df['8_policy_choice'])

3.0
3.0
3.0
2.0
3.0
3.0
3.0
3.0
336    3.0
Name: 1_policy_choice, dtype: float64 336    3.0
Name: 2_policy_choice, dtype: float64 336    3.0
Name: 3_policy_choice, dtype: float64 336    2.0
Name: 4_policy_choice, dtype: float64 336    3.0
Name: 5_policy_choice, dtype: float64 336    3.0
Name: 6_policy_choice, dtype: float64 336    3.0
Name: 7_policy_choice, dtype: float64 336    3.0
Name: 8_policy_choice, dtype: float64

In [180]:
#export to csv
df_pivot.to_csv(r"C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_2\Data\Part2_data_to_rows.csv", index=False)