In [34]:
import pandas as pd
import numpy as np
import math

## Import data

In [35]:
file1 = r'C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_1\Rearrange_datasets\part1_text.xlsx'

xl1 = pd.ExcelFile(file1)      # Load spreadsheet
df1 = xl1.parse('Sheet1')    # Load a sheet into a DataFrame by name: df1
df1.index  = np.arange(len(df1))

In [36]:
file2 = r'C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_1\Rearrange_datasets\part2_text.xlsx'

xl2 = pd.ExcelFile(file2)      # Load spreadsheet
df2 = xl2.parse('Sheet1')    # Load a sheet into a DataFrame by name: df1
df2.drop(['participant.time_started','participant.code','participant.id_in_session','mod'], inplace=True, axis=1)
df2.index  = np.arange(len(df2))

In [37]:
file3 = r'C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_1\Rearrange_datasets\part3_text.xlsx'

xl3= pd.ExcelFile(file3)      # Load spreadsheet
df3 = xl3.parse('Sheet1')    # Load a sheet into a DataFrame by name: df1
df3.drop(['participant.time_started','participant.code','participant.id_in_session','mod'], inplace=True, axis=1)
df3.index  = np.arange(len(df3))

## Concatenate the three parts

In [38]:
result = pd.concat([df1,df2,df3], axis=1)
result.drop(['Unnamed: 0'], inplace=True, axis=1)

In [39]:
#discard rows in result dataframe that have more that 10 nan values
result = result.replace('-', np.nan)
result = result.dropna(thresh=10)
result.reset_index(drop=True, inplace=True)

result.to_excel(r'C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_1\Rearrange_datasets\all_parts.xlsx')

In [40]:
pd.set_option('display.max_rows', None)
result.iloc[258:260]

,participant.id_in_session,mod,participant.code,participant.time_started,player.inequality_perception,What type of society do you think is Spain today – which diagram comes the closest?,player.inequality_wish,What do you think Spain ought to be like – which would you prefer?,player.income_distribution,How fair do you think the wealth distribution is in your country?,...,player.tax,Tax revenues should be used to help those who are more in need:,player.comments,session.label,session.experimenter_name,session.time_scheduled,session.time_started,session.mturk_HITId,session.mturk_HITGroupId,session.comment
258,274,2,bru6v3n9,2022-07-18 20:52:56.394875+00:00,3.0,C,5.0,E,4.0,Very unfair,...,7.0,7,"ha estado muy bien, espero que mi participació...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,276,4,whkaijsr,2022-07-18 23:12:33.622477+00:00,3.0,C,5.0,E,3.0,Unfair,...,6.0,6,,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Madrid participants only

In [41]:
for i in range(283):
    if result['The participant lives in Madrid:'][i]=='No':
        result=result.drop(i)
result.index  = np.arange(len(result))

In [42]:
np.shape(result)

(181, 250)

In [43]:
result.head()

,participant.id_in_session,mod,participant.code,participant.time_started,player.inequality_perception,What type of society do you think is Spain today – which diagram comes the closest?,player.inequality_wish,What do you think Spain ought to be like – which would you prefer?,player.income_distribution,How fair do you think the wealth distribution is in your country?,...,player.tax,Tax revenues should be used to help those who are more in need:,player.comments,session.label,session.experimenter_name,session.time_scheduled,session.time_started,session.mturk_HITId,session.mturk_HITGroupId,session.comment
0,2,2,iu9re9u5,2022-07-18 13:56:52.428815+00:00,3.0,C,4.0,D,3.0,Unfair,...,3.0,3,gracias,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4,4,76mq2acd,2022-07-18 21:47:35.300273+00:00,3.0,C,4.0,D,3.0,Unfair,...,3.0,3,Buen trabajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5,1,n6c69l1z,2022-07-18 22:45:11.140948+00:00,3.0,C,4.0,D,2.0,Fair,...,6.0,6,todo correcto,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,4,p7eprbp3,2022-07-18 10:05:54.744504+00:00,2.0,B,5.0,E,3.0,Unfair,...,5.0,5,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,3,epujf994,2022-07-18 10:53:49.868989+00:00,3.0,C,4.0,D,4.0,Very unfair,...,5.0,5,Espero que no utilicen estos datos para aplica...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
result.to_excel(r'C:\Users\PcLaptop\Documents\GitHub\APlanet\Pilot_1\Rearrange_datasets\all_Madrid.xlsx')